"""empty message

Revision ID: 647683b6dc30
Revises: 
Create Date: 2019-11-17 05:39:34.479483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647683b6dc30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('day', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('month', sa.String(length=12), nullable=True))
    op.add_column('users', sa.Column('year', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'year')
    op.drop_column('users', 'month')
    op.drop_column('users', 'day')
    # ### end Alembic commands ###
